swagger: '2.0'
basePath: /cart-management/v1
host: localhost
info:
  title: Cart Management
  version: v1
  description: Cart Management API
paths:
  /cart/checkout:
    post:
      parameters:
        - in: body
          name: body
          description: Products to checkout
          required: true
          schema:
            type: object
            properties:
              products:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      example: 1
                    quantity:
                      type: number
                      example: 2
            required:
              - products
      responses:
        '200':
          description: OK
          schema:
            properties:
              data:
                type: object
                properties:
                  total_amount:
                    example: 1000
                  total_amount_with_discount:
                    example: 1000
                  total_discount:
                    example: 0
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          example: 1
                        quantity:
                          example: 2
                        unit_amount:
                          example: 500
                        total_amount:
                          example: 1000
                        discount:
                          example: 0
                        is_gift:
                          example: false
              messages:
                type: array
        '400':
          description: Bad Request
          schema:
            properties:
              data:
                type: object
                example: null
              messages:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    description:
                      type: string
                example:
                  - code: E002
                    description: Invalid value to field
                    field: quantity
        '422':
          description: Unprocessable Entity
          schema:
            properties:
              data:
                type: object
                example: null
              messages:
                type: array
                items:
                  type: object
                  properties:
                    code:
                      type: string
                    description:
                      type: string
                example:
                  - code: E005
                    message: Unable to checkout empty cart
        '503':
          description: Service Unavailable
          schema:
            properties:
              data:
                type: object
                example: null
              message:
                $ref: '#/definitions/internal_server_error_messages'
      tags:
        - Cart
definitions:
  internal_server_error_messages:
    type: array
    items:
      type: object
      properties:
        code:
          type: string
        messages:
          type: string
    example:
      - code: E999
        message: Unknown error
